config/routes.rb
Railstom::Application.routes.draw do
  get '/' => 'home#locale_root'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # angular's templates
  get '/templates/*id' => 'templates#show', as: :template, format: false

  devise_for :users, only: :omniauth_callbacks, controllers: {
    omniauth_callbacks: 'omniauth_callbacks'
  }

  scope '/:locale', constraints: { locale: /[a-z]{2}((-|_)[a-zA-Z]{2})?/ } do
    root :to => 'home#index'

    devise_for :users, skip: :omniauth_callbacks, controllers: {
      registrations: 'registrations'
    }

    devise_scope :user do
      get '/users/reset_password' => 'registrations#reset_password', as: :reset_password_user_registration
      post 'auth/:provider/new' => 'omniauth_callbacks#new', as: :auth_at_provider
    end

    get '/locale_pages/*id' => 'pages#locale_show', as: :locale_page, format: false
    get '/pages/*id' => 'pages#show', as: :page, format: false

    resource :cancel_accounts, only: [:edit, :destroy]
    resource :user_settings, only: [:edit, :update] do
      member do
        get :authentication
      end
    end
  end

  require 'constraints/admin'
  constraints Constraint::Admin do
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
  end

  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
end

app/controllers/cancel_accounts_controller.rb
class CancelAccountsController < ApplicationController
  inject :user_service

  before_action :authenticate_user!

  def edit
    flash.now[:warning] = t('controllers.cancel_accounts.flash.not_set_password_html', url: edit_user_registration_path) unless current_user.password_changed?
  end

  def destroy
    if current_user.valid_password?(params[:user][:current_password])
      user_service.cancel_account!
      sign_out :user
      flash[:success] = t('controllers.cancel_accounts.flash.account_deleted')
      redirect_to after_sign_out_path_for(current_user)
    else
      flash.now[:error] = t('controllers.cancel_accounts.flash.not_valid_password')
      render :edit
    end
  end
end

app/views/cancel_accounts/edit.html.erb
<% content_for :my_account_content do %>
  <h2><%= t('devise.registrations.edit.cancel_my_account') %></h2>

  <p><%= t 'cancel_accounts.edit.message' %></p>

  <%= simple_form_for(current_user, url: cancel_accounts_path, method: :delete) do |f| %>
    <%= f.input :current_password, :required => true, placeholder: t('layouts.application.placeholders.password') %>

    <%= f.button :submit, t('devise.registrations.edit.cancel_my_account') %>
  <% end %>
<% end %>

<%= render 'common/my_account' %>