config/routes.rb
Railstom::Application.routes.draw do
  get '/' => 'home#locale_root'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # angular's templates
  get '/templates/*id' => 'templates#show', as: :template, format: false

  devise_for :users, only: :omniauth_callbacks, controllers: {
    omniauth_callbacks: 'omniauth_callbacks'
  }

  scope '/:locale', constraints: { locale: /[a-z]{2}((-|_)[a-zA-Z]{2})?/ } do
    root :to => 'home#index'

    devise_for :users, skip: :omniauth_callbacks, controllers: {
      registrations: 'registrations'
    }

    devise_scope :user do
      get '/users/reset_password' => 'registrations#reset_password', as: :reset_password_user_registration
      post 'auth/:provider/new' => 'omniauth_callbacks#new', as: :auth_at_provider
    end

    get '/locale_pages/*id' => 'pages#locale_show', as: :locale_page, format: false
    get '/pages/*id' => 'pages#show', as: :page, format: false

    resource :cancel_accounts, only: [:edit, :destroy]
    resource :user_settings, only: [:edit, :update] do
      member do
        get :authentication
      end
    end
  end

  require 'constraints/admin'
  constraints Constraint::Admin do
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
  end

  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
end

app/controllers/user_settings_controller.rb
class UserSettingsController < ApplicationController
  before_action :authenticate_user!

  def edit
  end

  def update
    if current_user.update_attributes(user_params)
      flash[:success] = t('.successfully_saved')
      redirect_to edit_user_settings_url
    else
      render :edit
    end
  end

  def authentication
  end

  private

  def user_params
    permitted = [:avatar, :avatar_cache, :remove_avatar, :enabled_newsletter, :preferred_language]

    if params[:user][:nickname].present? || current_user.nickname.present?
      permitted << :nickname
    end

    params.require(:user).permit(*permitted)
  end
end

app/helpers/user_settings_helper.rb
module UserSettingsHelper
  def display_link_to_connect_with_provider(provider, icon, link_message, linked_message)
    icon_html = %{<i class="fa fa-#{icon} fa-lg"></i>}

    if current_user.has_provider?(provider)
      raw "#{icon_html} #{linked_message}"
    else
      link_to raw("#{icon_html} #{link_message}"), user_omniauth_authorize_path(provider), data: { 'load-icon' => 'append', 'load-icon-margin' => 'left:10px' }
    end
  end
end

app/views/user_settings/authentication.html.erb
<% content_for :my_account_content do %>
  <h2><%= t('.title') %></h2>

  <%= display_link_to_connect_with_provider(:facebook, 'facebook-square', t('.providers.link_facebook'), t('.providers.linked_facebook')) %>
<% end %>

<%= render 'common/my_account' %>

app/views/user_settings/edit.html.erb
<% content_for :my_account_content do %>
  <h2><%= t('.title') %></h2>

  <%= simple_form_for(current_user, url: user_settings_path) do |f| %>
    <div class="row extra-margin-top">
      <div class="large-12 columns">
        <%= f.input :nickname, label: t('.labels.nickname'), hint: t('.hints.nickname') %>
      </div>
    </div>

    <div class="row">
      <div class="large-12 columns">
        <%= image_tag current_user.avatar.normal.url, class: 'th' %>
      </div>
    </div>
    <div class="row extra-margin-top">
      <div class="large-12 columns">
        <%= f.input :avatar, label: t('.labels.avatar') %>
      </div>
    </div>

    <% if current_user.avatar? %>
      <div class="row extra-margin-top">
        <div class="large-12 columns">
          <%= f.input :remove_avatar, as: :boolean, label: t('.labels.remove_avatar') %>
        </div>
      </div>
    <% end %>

    <div class="row extra-margin-top">
      <div class="large-12 columns">
        <%= f.input :enabled_newsletter, as: :boolean, label: t('.labels.enabled_newsletter') %>
      </div>
    </div>

    <div class="row extra-margin-top">
      <div class="large-12 columns">
        <%= f.input :preferred_language, collection: Locale.collection_of_languages, include_blank: false, label: t('.labels.preferred_language') %>
      </div>
    </div>

    <div class="row extra-margin-top">
      <div class="large-12 columns">
        <%= f.hidden_field :avatar_cache %>
        <%= button_tag t('layouts.application.buttons.save'), data: { 'load-icon' => 'append', 'load-icon-margin' => 'left:10px' } %>
      </div>
    </div>
  <% end %>
<% end %>

<%= render 'common/my_account' %>