config/routes.rb
Railstom::Application.routes.draw do
  get '/' => 'home#locale_root'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # angular's templates
  get '/templates/*id' => 'templates#show', as: :template, format: false

  devise_for :users, only: :omniauth_callbacks, controllers: {
    omniauth_callbacks: 'omniauth_callbacks'
  }

  scope '/:locale', constraints: { locale: /[a-z]{2}((-|_)[a-zA-Z]{2})?/ } do
    root :to => 'home#index'

    devise_for :users, skip: :omniauth_callbacks, controllers: {
      registrations: 'registrations'
    }

    devise_scope :user do
      get '/users/reset_password' => 'registrations#reset_password', as: :reset_password_user_registration
      post 'auth/:provider/new' => 'omniauth_callbacks#new', as: :auth_at_provider
    end

    get '/locale_pages/*id' => 'pages#locale_show', as: :locale_page, format: false
    get '/pages/*id' => 'pages#show', as: :page, format: false

    resource :cancel_accounts, only: [:edit, :destroy]
    resource :user_settings, only: [:edit, :update] do
      member do
        get :authentication
      end
    end
  end

  require 'constraints/admin'
  constraints Constraint::Admin do
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
  end

  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
end

app/views/common/_my_account.html.haml
%h1
  = t('_my_account.title')
  %small.subheader= current_user.email

.row
  .small-9.columns
    = yield(:my_account_content)
  .small-3.columns
    %ul.side-nav
      = menu_items({ name: t('_my_account.user_settings'), path: [edit_user_settings_path, {controller: 'user_settings', action: 'update'}] },
        { name: t('_my_account.authentication'), path: [authentication_user_settings_path] },
        { name: t('_my_account.account_settings'), path: [edit_user_registration_path, {controller: 'registrations', action: 'update'}] },
        { name: t('_my_account.cancel_account'), path: [edit_cancel_accounts_path, {controller: 'cancel_accounts', action: 'destroy'}] })

app/views/common/_my_account.html.slim
h1
  => t('_my_account.title')
  small.subheader = current_user.email

.row
  .small-9.columns
    = yield(:my_account_content)
  .small-3.columns
    ul.side-nav
      = menu_items(\
        { name: t('_my_account.user_settings'), path: [edit_user_settings_path, {controller: 'user_settings', action: 'update'}] },
        { name: t('_my_account.authentication'), path: [authentication_user_settings_path] },
        { name: t('_my_account.account_settings'), path: [edit_user_registration_path, {controller: 'registrations', action: 'update'}] },
        { name: t('_my_account.cancel_account'), path: [edit_cancel_accounts_path, {controller: 'cancel_accounts', action: 'destroy'}] })